### ISSUE TITLE
Multi-GPU support: OOM error with dual RTX 3090

### ISSUE THREAD

**Issue by Ksdb104** [Luce-Org/luce-megakernel#42]
Hi, I'm testing the project on a dual-GPU setup (2× RTX 3090, 24GB VRAM each). However, I'm encountering an Out-Of-Memory (OOM) error during initialization. 

The logs show the backend attempting to allocate ~27.26 GB on `Device 0`, which exceeds its available VRAM (24.12 GB). 

Could you please clarify if multi-GPU support (e.g., tensor splitting or layer distribution across GPUs) is implemented? If so, how should I configure it to properly split the model across both cards? Any relevant config keys or CLI flags would be greatly appreciated.

**Error Log:**
```bash
[cfg] seq_verify=0 fast_rollback=1 ddtree=1 budget=22 temp=1.00 chain_seed=1 fa_window=2048
ggml_cuda_init: found 2 CUDA devices (Total VRAM: 48252 MiB):
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes, VRAM: 24126 MiB
  Device 1: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes, VRAM: 24126 MiB
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 27260.57 MiB on device 0: cudaMalloc failed: out of memory
alloc_tensor_range: failed to allocate CUDA0 buffer of size 28584775680
target load: ggml_backend_alloc_ctx_tensors failed (target)
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [157036]

**Comment by davide221** [comment]
Multi-GPU is not currently supported, we are working on some cool stuff for tensor splitting and heterogeneus setups.
Any contribution to bring early support for this is very appreciated

**Comment by efschu** [comment]
Thanks for your great work. I can't wait to see more. It would also be great to better adjust the KV cache, like having different quantization levels for K and V. But heterogeneus split tensor ... wow. Maybe you want to have a look at ik_llama split mode graph.

**Comment by davide221** [comment]
Thanks for the suggestion! Turboquant integration is the work of @mraxai so i tag him here

**Comment by efschu** [comment]
Trying this with opencode give tool call errors and Thinking loops.

**Comment by davide221** [comment]
@efschu can you open an issue with your specific settings so that we can fix it?

**Comment by dusterbloom** [comment]
@davide221 I wish I had another 3090 to test this and fix it. I can try but hard to test from here

**Comment by dusterbloom** [comment]
> Trying this with opencode give tool call errors and Thinking loops.

@efschu 
I notice lots of looping too when using `opencode` with GLM5. 
Can you try to see if the same loops happen on `pi.dev` or any other good harness?

**Comment by sanastasiou** [comment]
If u manage to add multi gpu support on this repo with any of the known frameworks.. noone will ever use anything else ever again with 3090s. Something to think about :)

**Comment by davide221** [comment]
@sanastasiou we just added dual GPU support, let us know if you try it out 🚀

**Comment by sanastasiou** [comment]
@davide221  I alredy saw this on x.com and wanted to try it!!!!!!!!!!!!!!!! But if I understood correctly is only for a combo of drafter + "decoder" GPU ? Correct? 

Meaning, I could marry a 3080 with e.g. a 3090 or any combination thereof, but I do not have a benefit yet, of e.g. dual 3090s running in parallel correct?

**Comment by noonghunna** [comment]
For anyone hitting this on dual 3090: PR #80 (merged 2026-05-04) added the daemon-binary flags `--target-gpu` / `--draft-gpu` / `--draft-feature-mirror` to split target and draft across cards. Verified via `strings test_dflash` and the daemon's `[cfg]` line at boot:

```
[daemon] [cfg] ... draft_feature_mirror=1 target_gpu=0 draft_gpu=1
```

The catch: **`server.py` doesn't forward these flags to the daemon subprocess.** The OpenAI-compatible serving path can't access PR #80's split today. The standalone `bench_pflash_phase_split.py` does pass them through, which is why the bench harness works on dual-GPU but `server.py` still OOMs.

Local workaround — small edit in `build_app()` after the `cmd = [...]` list:

```python
cmd = [bin_abs, str(target), str(draft), "--daemon",
       "--fast-rollback", "--ddtree", f"--ddtree-budget={budget}",
       f"--max-ctx={max_ctx}",
       f"--stream-fd={stream_fd_val}"]
_t_gpu = os.environ.get("LUCEBOX_TARGET_GPU")
_d_gpu = os.environ.get("LUCEBOX_DRAFT_GPU")
if _t_gpu is not None:
    cmd.append(f"--target-gpu={_t_gpu}")
if _d_gpu is not None:
    cmd.append(f"--draft-gpu={_d_gpu}")
if os.environ.get("LUCEBOX_DRAFT_FEATURE_MIRROR", "0") not in ("0", "", "false", "False"):
    cmd.append("--draft-feature-mirror")
```

Then boot with:

```bash
LUCEBOX_TARGET_GPU=0 LUCEBOX_DRAFT_GPU=1 LUCEBOX_DRAFT_FEATURE_MIRROR=1 \
  python scripts/server.py --target ... --draft ... --port 8004 ...
```

VRAM lands ~17.5 GiB on GPU 0 (target + KV) and ~3.5 GiB on GPU 1 (draft) instead of all-on-GPU-0. Holding off on a PR pending maintainer preference on flag naming (CLI flags vs env vars vs both); happy to send one if it'd help.

Confirmed working on 2× RTX 3090 PCIe (no NVLink). Note: `nvidia-smi topo -p2p r` shows `CNS` (Chipset Not Supported) on consumer boards, so peer-to-peer copies fall back to host-mediated transfers — the dual-GPU split fixes the OOM but isn't free per-token.

A separate bug surfaces on the 3rd compress cycle (CUDA illegal-mem-access during `cudaFree`) — filing that one separately.

**Comment by noonghunna** [comment]
Cross-link: filed the 3rd-cycle CUDA illegal-mem-access as #95.

**Comment by efschu** [comment]
So running on 2x20GB 3080s should be possiblen now? Also wird pflash?

**Comment by noonghunna** [comment]
@efschu — short answer: **DFlash should work on 2× 20 GB; PFlash is not ready yet** (separate upstream bug, see below).

## DFlash on 2× 3080 modded 20 GB

With the env-var server.py patch from my comment above (`LUCEBOX_TARGET_GPU=0 LUCEBOX_DRAFT_GPU=1 LUCEBOX_DRAFT_FEATURE_MIRROR=1`), the VRAM split is:

- **GPU 0**: target Q4_K_M (~15 GB) + KV pool + activations
- **GPU 1**: dflash draft (~3.5 GB)

That fits comfortably on 24 GB / 3090 (validated cross-rig). On 20 GB / 3080 modded the math is tighter: GPU 0 has ~5 GB instead of ~9 GB of headroom for KV pool + activations after the target loads. Should still work but you'll want to:

- Lower `--max-ctx` from `65536` → `32768` initially, then probe up. Each 32K of ctx costs ~2 GB KV at fp8 (single-stream).
- If you build with K8V4 KV (`-ctk q8_0 -ctv q4_0` flags via the daemon), you save ~30% per-token KV vs fp8 — same trade-off pattern as [@efschu's club-3090 #47](https://github.com/noonghunna/club-3090/issues/47) where TQ3 → fp8 swap was needed on 20 GB cards. The lucebox K8V4 KV path is the equivalent here.
- Watch boot log for `Available KV cache memory: X GiB` line — if X is close to 0, lower `--max-ctx` further.

DFlash decode on 2× 20 GB should land in the 60-90 TPS range based on the math (slower than 2× 3090 due to 20 GB cards being PCIe x4/x8 in your topology — same constraints from #47 apply on lucebox too).

## PFlash on 2× 20 GB — not yet

PFlash hits a different bug: **CUDA illegal-mem-access on the 3rd compress cycle**, regardless of GPU layout. Filed as [#95](https://github.com/Luce-Org/lucebox-hub/issues/95). Reproduces on both single-GPU and dual-GPU configurations on 24 GB / 3090 — your 20 GB cards would hit the same. So PFlash via `server.py` isn't ready on any rig until that gets fixed upstream.

PFlash *standalone* (the `bench_pflash_phase_split.py` harness) does work — that's the path @weicj's published 24K → 262K NIAH numbers use. But the OpenAI-compatible serving path (which is what most users want) is blocked by #95.

## TL;DR

- **DFlash on 2× 20 GB via lucebox**: should work, lower max-ctx + use K8V4 KV. Try it; report back if you hit OOM and we'll iterate.
- **PFlash on 2× 20 GB**: blocked on upstream bug #95. Not specific to your hardware.

## Important — these are not formal recommendations yet

Worth being explicit: we (club-3090) are tracking DFlash and PFlash with interest — both touch hardware/regimes our stack cares about — but **neither is a concrete recommendation today**. The lucebox-hub project is moving fast (4 substantial PRs landed in the last week alone — #78 dual-GPU PFlash split, #80 DFlash target/draft split, plus the 3rd-cycle CUDA bug we just filed at #95). Anything that works today might be replaced by a different code path tomorrow, and the failure modes shift with each pin.

**Until lucebox-hub cuts a stable release**, we're treating DFlash + PFlash on club-3090 as exploratory only:
- Bench data goes in `BENCHMARKS.md` under "Cross-engine — Luce DFlash" / "PFlash long-context" subsections, **not** as ranked variants in the picker tools (`launch.sh` / `switch.sh`).
- Documentation pointers say "watch + experiment", not "switch your daily driver to this".
- We file upstream bugs (like #95) but don't carry local patches in `models/qwen3.6-27b/lucebox/` or similar.

For agentic / coding daily-driver work on 2× 20 GB, the well-validated cross-rig paths are still vLLM `dual.yml` (TP=2 fp8 KV) or `dual-turbo.yml` (your existing fp8_e5m2 swap from #47). Both have a track record of multi-week stability. Treat lucebox results as data points, not deployment guides — for now.

I'll update this stance the moment lucebox-hub publishes a tagged release we can pin to.

**Comment by weicj** [comment]
Thanks for looking into this and sharing the workaround. The lack of `server.py` wiring was not meant to be a functional gap in those earlier PRs, but rather a scope decision.

The PFlash phase-split and DFlash dual-GPU split changes were intentionally kept to the benchmark/daemon harness path, so the GPU placement and lifecycle behavior could be validated in isolation. OpenAI-compatible server integration touches a broader serving lifecycle: request routing, daemon reuse, park/unpark, model reload/free, cache ownership, and generation recovery. I thought it would be better handled as a separate serving-focused change. That said, I agree the server path still needs to be wired up. If you already have a candidate PR in progress, I would be happy to help test it.

I also tried to reproduce #95 locally. My box is dual 2080 Ti / SM75, so it is not a perfect match. Clean upstream/main hits a separate SM75/BF16 FlashPrefill assertion before reaching the reported third-cycle `cudaFree` crash. On my SM75 FP16 path, PFlash compression itself works; a target-only three-cycle run passes, while the full target+draft restore path OOMs on 22GB.

So I cannot fully reproduce the 3090 crash here, but since the report reproduces on both single-GPU and dual-GPU 3090, it does not look P2P/NVLink-specific. For further diagnosis, I would first inspect stale `sg` / `draft_sg` / `proj_sg` / feature-mirror state and CUDA synchronization around repeated park/free/unpark cycles.

**Comment by kbradsha** [comment]
Has anyone tested this with the environment variable GGML_CUDA_ENABLE_UNIFIED_MEMORY=1?
